### ISSUE TITLE
Not getting access token using B2C. 

### ISSUE THREAD

**Issue by aarsan** [Azure-Samples/ms-identity-python-webapp#10]
When trying to make a graph call to the /me endpoint, I am not getting an access token. I do get an id token, however.

**Comment by rayluo** [comment]
Admittedly, our [README_B2C only mentions how to get an access token for an web api hosted inside your B2C tenant](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/master/README_B2C.md#access-a-web-api), but we did not try the MS graph. What is your configuration setting for the SCOPE?

I'm also looping in PM @archieag who might be more familiar in this particular usage.

**Comment by aarsan** [comment]
I've tried various scopes with different failures but the one I'm trying now is: 'https://graph.microsoft.com/.default'

**Comment by rayluo** [comment]
It turns out a B2C app is not currently able to access MS graph api. MS Graph is an AAD resource, not a B2C resource.

Since last year, the B2C team is working to combine the AAD and B2C, but it takes time. When that happens, this sample would be able to acquire the token.

PS: Thanks @jennyf19 for confirming this, while in her business trip in the other side of the earth!
