### ISSUE TITLE
Flask-Session version

### ISSUE THREAD

**Issue by KillyMcDead** [Azure-Samples/ms-identity-python-webapp#30]
The requirements.txt needs to be updated to flask_session == 0.3.1 due to
https://github.com/fengsp/flask-session/issues/119

**Comment by rayluo** [comment]
We can not go back to flask_session 0.3.1 because it was not up-to-date and caused lots of noise in this repo's issues history.

I used a similar workaround in my fork, and then one user here suggested [an improvement](https://github.com/rayluo/flask-session/pull/3). I've just sent my improvement as [a PR to the upstream repo](https://github.com/fengsp/flask-session/pull/122).

That's all I could do, for now. I do not have control on how soon it will be accepted in that repo. If it won't happen within a week or so, we will probably have to bring [my workaround back from its retirement](https://github.com/Azure-Samples/ms-identity-python-webapp/pull/27). :-/

**Comment by mattfeltonma** [comment]
Workaround for this is to install the latest version of [cachelib](https://github.com/pallets/cachelib).  An [update](https://github.com/pallets/cachelib/commit/fa376861b7e8364531e0f673ee97a8278897c3e0) was added last month to address the issue where sessions were not committing to disk.  While the update was committed to the master branch of the repo, the package on PyPi is still old.  I worked around this by adding "-e git+git://github.com/pallets/cachelib.git@master#egg=cachelib" to the requirements.txt.

**Comment by rayluo** [comment]
Thanks @mattfeltonma for the hint! [I've left a comment in the cachelib repo to ping the repo owner](https://github.com/pallets/cachelib/pull/12#issuecomment-644301902).

Meanwhile, "adding `-e git+git://github.com/pallets/cachelib.git@master#egg=cachelib` to the requirements.txt" remains one of the viable workaround. So we can kind of document it here.

But it is uncomfortable for us to officially add a skip-level requirement `"-e git+git://github.com/pallets/cachelib.git@master#egg=cachelib`, especially without proper versioning semantic, into our sample code base. If pressed, I would rather temporarily [bring my workaround back from its retirement](https://github.com/Azure-Samples/ms-identity-python-webapp/pull/27).

**Comment by mattfeltonma** [comment]
Makes sense @rayluo.

**Comment by rayluo** [comment]
@KillyMcDead @mattfeltonma 
That upstream fix (https://github.com/pallets/cachelib/pull/12) was released in its `0.1.1` version 7 hours ago. It will be automatically picked up if you have a new install of this MSAL Web App sample, or you could update your environment by `pip install --upgrade cachelib`.

Please let us know whether that upgrade would fix this issue.

**Comment by rayluo** [comment]
> Please let us know whether that upgrade would fix this issue.

No news is good news. We are closing this issue. Feel free to reopen if you find new issues.
