### ISSUE TITLE
State parameter for multi tenant web app.

### ISSUE THREAD

**Issue by chandraguptab** [Azure-Samples/ms-identity-python-webapp#84]
Hi, my web app should send application-specific `state parameter` such as subdomain URL where the user originated, so that my middleware can redirect the user to the correct subdomain after sign-in.

How can I send the `state parameter` to `https://login.microsoftonline.com/common`?

I am refering to the [Microsoft doc](https://docs.microsoft.com/en-gb/azure/active-directory/develop/reply-url#use-a-state-parameter)

**Comment by rayluo** [comment]
Thanks for your patience, @chandraguptab . It was not possible back then when you created this issue. But, since [version 0.4+ of this sample](https://github.com/Azure-Samples/ms-identity-python-webapp/releases), you can now set your own state by adding `state="my_own_state",` before [this line](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/0.5.0/app.py#L33). Cheers!
